### ISSUE TITLE
Add support for Linux 2.4

### ISSUE THREAD

**Issue by Lili1228** [charliesome/doslinux#1]
Linux 2.4.37.11 was the last version of a kernel to (reliably) support UMSDOS, which adds Linux permissions to FAT partitions. There's also [a site](http://linux.voyager.hr/umsdos/) to add UVFAT (UMSDOS combined with VFAT == LFN) support to the 2.4.19, which patches successfully on 2.4.24 and requires some renaming on 2.4.25-2.4.37.11.

Considering DOS == FAT, this can make implementing rootfs much easier.

**Comment by haileys** [comment]
It looks like Linux 2.4's [boot protocol](https://www.kernel.org/doc/html/latest/x86/boot.html#the-linux-x86-boot-protocol) is incompatible with what's currently in use. It would be possible to check the `version` field of the real mode kernel header and handle older boot protocols accordingly, but I don't intend to work on this myself. There may be other incompatibilities too. I would accept pull requests around this though if it's a project you would like to take on.

**Comment by tpimh** [comment]
@mariuszkurek It makes much more sense to make UMSDOS work on more recent kernels, doesn't it?

**Comment by Lili1228** [comment]
Sense, but also work.
