### ISSUE TITLE
I'm bit confused by what this is ?

### ISSUE THREAD

**Issue by stuaxo** [charliesome/doslinux#3]
Can some more information be added to the README ?

Is the name a pun, or does this run in WIndows, a bit like WSL ?

The screenshot shows it running in QEMU, I'm confused...

**Comment by NitroNils** [comment]
Yes, does it run in the WSL or in Linux?

Finally I can.make use of my DOS for Dummies-book!

**Comment by lefnire** [comment]
You silly goose.
