### ISSUE TITLE
Add support for using a FreeDOS image

### ISSUE THREAD

**Issue by dragon788** [charliesome/doslinux#7]
FreeDOS is pretty much a drop in replacement in most cases and has a lot more recent development and less licensing concerns. Plus FOSS is great.

**Comment by haileys** [comment]
FreeDOS does work - you can simply install it on `hdd.base.img` instead of MS-DOS

**Comment by lpsantil** [comment]
You can use one of the HDD images here (http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/qemu/).
