### ISSUE TITLE
Cannot initialize 'C:'

### ISSUE THREAD

**Issue by ri0t** [charliesome/doslinux#9]
Tried this with a qcow image i generated via http://gunkies.org/wiki/Installing_MS-DOS_on_Qemu - which resulted in:
> ➜ make
> nasm -o doslinux.com -f bin doslinux.asm
> i386-linux-musl-gcc -m32 -static -Os -Wall -Wextra -o init/init.o -c init/init.c
> i386-linux-musl-gcc -m32 -static -Os -Wall -Wextra -o init/vm86.o -c init/vm86.c
> i386-linux-musl-gcc -m32 -static -Os -Wall -Wextra -o init/panic.o -c init/panic.c
> i386-linux-musl-gcc -m32 -static -Os -Wall -Wextra -o init/kbd.o -c init/kbd.c
> i386-linux-musl-gcc -m32 -static -Os -Wall -Wextra -o init/term.o -c init/term.c
> i386-linux-musl-gcc -m32 -static -Os -Wall -Wextra -o init/init init/init.o init/vm86.o init/panic.o init/kbd.o init/term.o
> cp hdd.base.img hdd.img
> MTOOLSRC=mtoolsrc mmd C:/doslinux
> init C: non DOS media
> Cannot initialize 'C:'
> make: *** [Makefile:19: hdd.img] Error 1

**Comment by haileys** [comment]
I don't think mtools supports qcow. You will need to convert the qcow to a flat image.
